swagger: '2.0'
info:
  $ref: ./info.yaml
tags:

  - name: Сущности пользователя Эвотор
    description:
      Запросы информации о магазинах, сотрудниках и смарт-терминалах определённого пользователя платформы Эвотор.

  - name: Вебхуки-запросы
    description:
      Запросы к стороннему сервису. Облако Эвотор ожидает подтверждения этих запросов. Время ожидания -- 10 секунд.

  - name: Товары и документы
    description: |
      Запросы общей информации о товарах и документах определённого магазина (`storeUuid`) пользователя платформы Эвотор.

      Запросы для работы со схемами и дополнительными полями товаров смотрите в разделе **Схемы и дополнительные поля товаров**.

  - name: Схемы и дополнительные поля товаров
    description:
      Запросы для работы с дополнительными полями и схемами товаров.

  - name: Вебхуки-уведомления
    description:
      События, на которые сторонний сервис может подписаться. Облако Эвотор считает, что сообщение доставлено, если сторонний сервиси ответил 200 ОК.

  - name: Данные ОФД
    description:
      Данные ОФД.

#  - name: Не рекомендуется
#    description:
#      Использование метода не рекомендуется, так как метод устарел.
#    x-traitTag: true

produces:
    - application/json
consumes:
    - application/json
x-servers:
  - url: //
    description: 'Веб-адрес запроса:'
schemes:
    - https
paths:
  $ref: ./paths.yaml
parameters:
  $ref: ./parameters.yaml
definitions:
  $ref: ./definitions.yaml
