swagger: '2.0'
info:
  $ref: ./evotorCallbacks/info.yaml
tags:
  - name: Учётные записи в стороннем сервисе
    description: |
      Запросы от облака Эвотор к стороннему сервису для управления учётными записями.
  - name: Биллинг
    description: Запросы и события связанные с биллингом пользователей платформы и сторонних сервисов.
  - name: Сущности пользователя Эвотор
    description: |
      Изменения в Личном  кабинете пользователя платформы Эвотор дублируются в стороннем сервисе. Для дублирования, облако Эвотор обращается к стороннему сервису с запросами на создание / редактирование магазинов, сотрудников и терминалов.
  - name: Товары и документы
    description: Вызовы к системе партнера в контексте товароучетных сущностей
  - name: Поиск товара
    description: Запросы для поиска товаров в базе стороннего сервиса по штрихкоду или алкокоду (коду алкогольной продукции).
  - name: Отправка чека
    description: Отправляет в сторонний сервис упрощенную структуру документа.
host: partner.com
schemes:
  - https
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  $ref: ./evotorCallbacks/paths.yaml
parameters:
  $ref: ./evotorCallbacks/parameters.yaml
definitions:
  $ref: ./definitions.yaml
