auth:
  name: X-Authorization
  in: header
  description: |
      Токен Облака Эвотор, который можно получить одним из способов, описанных в разделе документации [**Авторизация запросов к Облаку Эвотор**](https://developer.evotor.ru/docs/doc_authorization.html).
  required: true
  type: string

contentType:
  name: Content-Type
  in: header
  description: |
      Тип данных, которые может содержать тело HTTP-запроса. Значение по умолчанию `application/json`
  required: true
  type: string
  default: application/json

serverAuth:
  name: Authorization
  in: header
  description: |
    [Токен приложения стороннего сервиса](https://developer.evotor.ru/docs/doc_evotor_api_authorization.html#serverToken) для авторизации вебхуков Облака Эвотор в стороннем сервисе.

    Токен зависит от типа авторизации: Basic или Bearer.
  required: true
  type: string
  pattern: '^(Bearer|Basic) [a-zA-Z0-9_=-]+$'
  example: Bearer evotor_token

clientAuth:
  name: Authorization
  in: header
  description: |
    [Токен пользователя приложения стороннего сервиса](https://developer.evotor.ru/docs/doc_evotor_api_authorization.html#usersToken) для авторизации вебхуков Облака Эвотор в стороннем сервисе.
  required: true
  type: string
  pattern: '^Bearer [a-zA-Z0-9_=-]+$'

Accept:
  name: Accept
  in: header
  description: Формат данных, которые должен поддерживать ресурс.
  required: true
  type: string
  default: "application/json;charset=UTF-8"

Content-Type:
  name: Content-Type
  in: header
  description: Формат и способ предоставления данных.
  type: string
  required: true
  default: "application/json;charset=UTF-8"

Accept-Charset:
  name: Accept-Charset
  in: header
  description: Поддерживаемые кодировки.
  type: string
  required: false
  default: "UTF-8"

Accept-Encoding:
  name: accept-encoding
  in: header
  description: Поддерживаемые форматы сжатия.
  type: string
  required: false
  default: "[gzip]"

storeUuid:
  name: storeUuid
  in: path
  description: |
    Идентификатор магазина в Облаке Эвотор, в рамках которого действует запрос.

    Формат – `uuid4`.
  required: true
  type: string
  pattern: >-
    ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89aAbB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
  example: 20170222-5A12-403A-80F6-75C361356826

productUuid:
  name: productUuid
  in: path
  description: |
    Идентификатор товара в Облаке Эвотор, для которого действует запрос.

    Формат – `uuid4`.
  required: true
  type: string
  pattern: |
    ^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
